Removes unused util
Traceback (most recent call last):
  File "pomo_state.py", line 5, in <module>
    from util import timedelta_str, read_stage_and_time, get_pct_completed, Stage
ImportError: cannot import name 'get_pct_completed' from 'util'